### ISSUE TITLE
Unclear how to run this

### ISSUE THREAD

**Issue by Karric** [Prof9/PixelPet#6]
The downloads section has a build for macOS and Linux, but the 'PixelPet' file inside has no clear file type. What is PixelPet the file? How do you 'run' it on macOS/Linux?

**Comment by Prof9** [comment]
Like you would any other executable:
```shell
chmod +x PixelPet
./PixelPet
```
![image](https://github.com/Prof9/PixelPet/assets/3768851/838474a3-f7a8-493e-9da0-333dd69c91c8)

Tip: try Google next time.
